[project]
name = "fotil"
version = "0.1.0"
description = "Camera photo & video processing utilities"
authors = [
    {name = "Chen Yufei", email = "cyfdecyf@gmail.com"},
]
dependencies = [
    "typer>=0.9.0",
    "msgspec>=0.18.6",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[project.scripts]
fotil = "fotil.cli.main:app"

[project.optional-dependencies]
extra = [
    "typer[all]>=0.9.0",
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
test = [
    "pytest>=8.1.1",
]

[tool.ruff]
line-length    = 90
target-version = "py311"

[tool.ruff.lint]
ignore = [
  "E501", # compatible with Black
  "FBT",  # flake8-boolean-trap
]
select = [
  "I",     # isort
  "N",     # pep8-naming
  "PGH",   # pygrep
  "UP",    # pyupgrade
  "EM101", # raw-string-in-exception
  "RUF",   # ruff checks
  "E",     # pycodestyle(error)
  "W",     # pycodestyle(warning)
  "F",     # pyflakes
  "B",     # flake8-bugbear
  "C4",    # flake8-comprehensions
  "ERA",   # flake8-eradicate/eradicate
  "FA100", # flake8-future-annotations
  "PIE",   # flake8-pie
  "PYI",   # flake8-pyi
  "RET",   # flake8-return
  "FBT",   # flake8-boolean-trap
  "SIM",   # flake8-simplify
  "TCH",   # flake8-type-checking
  "TID",   # flake8-tidy-imports
]
unfixable = [
  "ERA", # do not autoremove commented out code
]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = [
  "E401", # multiple-imports-on-one-line
]

[tool.ruff.lint.isort]
known-first-party   = ["fotil"]
lines-after-imports = 2
lines-between-types = 1

[tool.ruff.format]
quote-style = "single"
